"""empty message

Revision ID: c21877f0bdd6
Revises: c32dcc4a85ce
Create Date: 2019-06-23 13:14:01.873686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21877f0bdd6'
down_revision = 'c32dcc4a85ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
